// Face numbering orders for the convex-polyhedron (isohedral) dice.
//
// AUTO-GENERATED by scripts/generate_numbering.ts - but safe to hand-tweak.
//
// Each entry maps a die id to a numbering order. An order is an array indexed by
// (value - 1) holding the BUILD-ORDER index of the face that should carry that
// value: order[0] is the build index of the face that gets a "1", order[1] the
// face that gets a "2", and so on. The build order is the order faces come out
// of the die builder (orbitFace), so this is purely a reshuffle applied after
// build - no geometry maths at runtime.
//
// Chiral dice store a pair [leftHanded, rightHanded] because their two mirror
// forms have different geometry.
//
// To regenerate after changing a die's geometry:
//   bunx vite-node scripts/generate_numbering.ts
// To tweak by hand: swap two entries to move those values onto each other's
// faces (keep each array a permutation of 0..n-1).

export type NumberingOrder = Array<number> | [Array<number>, Array<number>];

export const numberingOrders: Record<string, NumberingOrder> = {
	// d6_skew (d6, chiral): [left, right]
	d6_skew: [
		[5, 2, 0, 3, 1, 4],
		[3, 4, 2, 1, 5, 0]
	],
	// d12_tetartoid (d12, chiral): [left, right]
	d12_tetartoid: [
		[6, 8, 0, 7, 5, 1, 4, 2, 10, 3, 11, 9],
		[6, 8, 0, 7, 5, 1, 4, 2, 10, 3, 11, 9]
	],
	// d24_deltoidal_icositetrahedron (d24)
	d24_deltoidal_icositetrahedron: [
		2, 4, 7, 1, 13, 11, 14, 8, 16, 19, 21, 22, 17, 18, 20, 23, 15, 9, 12, 10, 6, 0, 3, 5
	],
	// d24_tetrakis_hexahedron (d24)
	d24_tetrakis_hexahedron: [
		2, 11, 5, 16, 9, 0, 13, 22, 18, 7, 15, 23, 20, 12, 4, 17, 21, 14, 3, 10, 19, 6, 8, 1
	],
	// d24_pentagonal_icositetrahedron (d24, chiral): [left, right]
	d24_pentagonal_icositetrahedron: [
		[8, 9, 11, 10, 20, 21, 23, 22, 18, 19, 17, 16, 3, 2, 0, 1, 5, 4, 6, 7, 13, 12, 14, 15],
		[8, 9, 11, 10, 20, 21, 23, 22, 18, 19, 17, 16, 3, 2, 0, 1, 5, 4, 6, 7, 13, 12, 14, 15]
	],
	// d30_rhombic_triacontahedron (d30)
	d30_rhombic_triacontahedron: [
		21, 0, 8, 27, 18, 25, 6, 7, 22, 5, 28, 20, 9, 3, 19, 16, 2, 10, 15, 23, 4, 29, 12, 13, 26, 17,
		24, 11, 1, 14
	],
	// d60_deltoidal_hexecontahedron (d60)
	d60_deltoidal_hexecontahedron: [
		27, 21, 36, 53, 52, 22, 4, 50, 38, 29, 48, 42, 9, 41, 11, 2, 7, 39, 1, 40, 15, 13, 23, 59, 37,
		25, 44, 58, 20, 31, 24, 19, 57, 43, 30, 34, 56, 16, 10, 8, 47, 6, 32, 0, 5, 12, 46, 14, 45, 51,
		26, 33, 49, 3, 17, 55, 54, 35, 18, 28
	],
	// d60_pentakis_dodecahedron (d60)
	d60_pentakis_dodecahedron: [
		13, 58, 14, 57, 21, 42, 30, 24, 8, 49, 47, 32, 9, 39, 29, 50, 22, 41, 4, 0, 1, 59, 6, 16, 55,
		12, 43, 51, 27, 35, 28, 20, 44, 36, 19, 56, 15, 5, 52, 2, 3, 7, 38, 25, 45, 34, 40, 10, 31, 48,
		46, 11, 23, 33, 37, 26, 54, 17, 53, 18
	],
	// d60_pentagonal_hexecontahedron (d60, chiral): [left, right]
	d60_pentagonal_hexecontahedron: [
		[
			5, 7, 6, 58, 33, 16, 55, 37, 26, 14, 52, 35, 57, 46, 4, 3, 32, 21, 22, 12, 56, 19, 47, 49, 45,
			25, 44, 38, 59, 39, 0, 28, 1, 11, 54, 10, 34, 8, 17, 31, 15, 23, 20, 51, 36, 43, 9, 30, 48,
			27, 13, 53, 2, 24, 18, 50, 29, 41, 40, 42
		],
		[
			5, 7, 6, 58, 33, 16, 55, 37, 26, 14, 52, 35, 57, 46, 4, 3, 32, 21, 22, 12, 56, 19, 47, 49, 45,
			25, 44, 38, 59, 39, 0, 28, 1, 11, 54, 10, 34, 8, 17, 31, 15, 23, 20, 51, 36, 43, 9, 30, 48,
			27, 13, 53, 2, 24, 18, 50, 29, 41, 40, 42
		]
	]
};
